### ISSUE TITLE
`no_std` support?

### ISSUE THREAD

**Issue by WaffleLapkin** [archer884/xvii#9]
It seems like `xvii` can work in `no_std` context too - the only methods that require `std` are `to_{uppercase,lowercase}` (and there can be replacement that uses `fmt::Display` instead of converting to string)

**Comment by archer884** [comment]
Ok, I looked into doing this, but it definitely seems like a bigger job than just removing those methods. I'd be fine with offering a no_std feature or something, but I'm not clear on how. If you're interested, take a shot at implementing it and send me a PR.

**Comment by WaffleLapkin** [comment]
I'll make a PR (probably after you'll merge the existing ORs, so there will be fewer conflicts), but until then, can you reopen the issue?

**Comment by archer884** [comment]
As a matter of principle, I don't consider this to be an issue with the library, and it's not something I have the time to fix, so I kind of did a "closed - won't fix" thing, you know? I'll reopen it for the time being.
